name: Run tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v1

      - name: Set environment config
        run: cp .env.sample .env

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
          npm ci
        env:
          CI: true

      - name: Unit tests and lint
        run: |
          npm run test:unit
          npm run prettier:test
          npm run lint
        env:
          CI: true

      - name: Integration tests
        uses: cypress-io/github-action@v1
        with:
          build: npm run build
          start: npm start
          wait-on: http://localhost:3000
